version: '3.9'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    env_file:
      - .env
    ports:
      - '9000:9000'
    volumes:
      - simplemap-data:/var/app/current
      - /var/app/current/.env:/var/app/current/.env:ro
    networks:
      - simplemap
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    depends_on:
      - php
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - simplemap-data:/var/app/current
      - /var/app/current/.env:/var/app/current/.env:ro
    networks:
      - simplemap
networks:
  simplemap:
    driver: bridge
volumes:
  simplemap-data: