version: '3.9'
services:
  mysql:
    image: 'mysql:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'simplemap-data:/var/lib/mysql'
    ports:
      - '3306:3306'
    networks:
      - simplemap
  php:
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: unless-stopped
    environment:
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - mysql
    ports:
      - '9000:9000'
    volumes:
      - type: bind
        source: .
        target: /var/app/current
    networks:
      - simplemap
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile.development
    restart: unless-stopped
    depends_on:
      - php
      - mysql
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - type: bind
        source: .
        target: /var/app/current
    networks:
      - simplemap
  node:
    image: 'node:lts-slim'
    restart: unless-stopped
    command: npm run watch
    depends_on:
      - php
    volumes:
      - type: bind
        source: .
        target: /var/app/current
    working_dir: /var/app/current
    networks:
      - simplemap
networks:
  simplemap:
    driver: bridge
volumes:
  simplemap-data:
    driver: local